# Generated by Django 6.1.1 on 2026-09-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('BSc', 'BSc'), ('MSc', 'MSc')], max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Descripstion', models.TextField(default='')),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
    ]
