# Generated by Django 6.1.1 on 2026-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Descripstion',
            field=models.TextField(default=''),
        ),
    ]
